### ISSUE TITLE
Wrong values for Poland 2000 pcs codes

### ISSUE THREAD

**Issue by Krzysztof-FF** [ufz/geotiff#1]
In file epsg_pcs.inc, instead of

ValuePair(PCS_ETRS89_Poland_CS2000_zone_5,2176)
ValuePair(PCS_ETRS89_Poland_CS2000_zone_6,2177)
ValuePair(PCS_ETRS89_Poland_CS2000_zone_7,2177)
ValuePair(PCS_ETRS89_Poland_CS2000_zone_8,2178)

should be

ValuePair(PCS_ETRS89_Poland_CS2000_zone_5,2176)
ValuePair(PCS_ETRS89_Poland_CS2000_zone_6,2177)
ValuePair(PCS_ETRS89_Poland_CS2000_zone_7,2178)
ValuePair(PCS_ETRS89_Poland_CS2000_zone_8,2179)

See https://pl.wikipedia.org/wiki/Uk%C5%82ad_wsp%C3%B3%C5%82rz%C4%99dnych_2000 for reference.

**Comment by bilke** [comment]
This is an inofficial fork of GeoTIFF. Please report bugs to http://www.osgeo.org.
